development:
  stripe_secret_key: 'sk_test_51K990FSH597g16nH8cvOmC2Vv2F9wpeqofpAGdzIBaZrPgbL2VC2tZXhFXcyikA9eRT8EPHHsvx5akkgiODqC53f00XmHi0odd'
  stripe_publishable_key: 'pk_test_51K990FSH597g16nHWNnhPTaXqrkOjfl57aJ63IYcJHJv356RkN4NXLiqYfs9vOnXI4taK9KX50lpJ29GhHDd2ChU00F1D3hqzX'
  stripe_price_token_premium: 'price_1L2b3ZSH597g16nHxXO8QrDX'
  stripe_price_token_monthly: 'price_1LC11xSH597g16nH43TMvUgI'
  stripe_price_token_3_month: 'price_1LD02MSH597g16nHwx6WxH5L'
  stripe_price_token_6_month: 'price_1LD03HSH597g16nH0xcZnvSl'
  stripe_price_token_12_month: 'price_1LD044SH597g16nHLnBu1m0i'

test:
  stripe_secret_key: 'sk_test_51K990FSH597g16nH8cvOmC2Vv2F9wpeqofpAGdzIBaZrPgbL2VC2tZXhFXcyikA9eRT8EPHHsvx5akkgiODqC53f00XmHi0odd'
  stripe_publishable_key: 'pk_test_51K990FSH597g16nHWNnhPTaXqrkOjfl57aJ63IYcJHJv356RkN4NXLiqYfs9vOnXI4taK9KX50lpJ29GhHDd2ChU00F1D3hqzX'
  stripe_price_token_premium: 'price_1L2b3ZSH597g16nHxXO8QrDX'
  stripe_price_token_monthly: 'price_1LC11xSH597g16nH43TMvUgI'
  stripe_price_token_3_month: 'price_1LD02MSH597g16nHwx6WxH5L'
  stripe_price_token_6_month: 'price_1LD03HSH597g16nH0xcZnvSl'
  stripe_price_token_12_month: 'price_1LD044SH597g16nHLnBu1m0i'

staging:
  stripe_secret_key: 'sk_test_51K990FSH597g16nH8cvOmC2Vv2F9wpeqofpAGdzIBaZrPgbL2VC2tZXhFXcyikA9eRT8EPHHsvx5akkgiODqC53f00XmHi0odd'
  stripe_publishable_key: 'pk_test_51K990FSH597g16nHWNnhPTaXqrkOjfl57aJ63IYcJHJv356RkN4NXLiqYfs9vOnXI4taK9KX50lpJ29GhHDd2ChU00F1D3hqzX'
  stripe_price_token_premium: 'price_1L2b3ZSH597g16nHxXO8QrDX'
  stripe_price_token_monthly: 'price_1LC11xSH597g16nH43TMvUgI'
  stripe_price_token_3_month: 'price_1LD02MSH597g16nHwx6WxH5L'
  stripe_price_token_6_month: 'price_1LD03HSH597g16nH0xcZnvSl'
  stripe_price_token_12_month: 'price_1LD044SH597g16nHLnBu1m0i'

production:
  stripe_secret_key: 'sk_test_51K990FSH597g16nH8cvOmC2Vv2F9wpeqofpAGdzIBaZrPgbL2VC2tZXhFXcyikA9eRT8EPHHsvx5akkgiODqC53f00XmHi0odd'
  stripe_publishable_key: 'pk_test_51K990FSH597g16nHWNnhPTaXqrkOjfl57aJ63IYcJHJv356RkN4NXLiqYfs9vOnXI4taK9KX50lpJ29GhHDd2ChU00F1D3hqzX'
  stripe_price_token_premium: 'price_1L2b3ZSH597g16nHxXO8QrDX'
  stripe_price_token_monthly: 'price_1LC11xSH597g16nH43TMvUgI'
  stripe_price_token_3_month: 'price_1LD02MSH597g16nHwx6WxH5L'
  stripe_price_token_6_month: 'price_1LD03HSH597g16nH0xcZnvSl'
  stripe_price_token_12_month: 'price_1LD044SH597g16nHLnBu1m0i'