development:
  stripe_secret_key: 'sk_test_51K990FSH597g16nH8cvOmC2Vv2F9wpeqofpAGdzIBaZrPgbL2VC2tZXhFXcyikA9eRT8EPHHsvx5akkgiODqC53f00XmHi0odd'
  stripe_publishable_key: 'pk_test_51K990FSH597g16nHWNnhPTaXqrkOjfl57aJ63IYcJHJv356RkN4NXLiqYfs9vOnXI4taK9KX50lpJ29GhHDd2ChU00F1D3hqzX'

production:
  stripe_secret_key: 'sk_test_51K990FSH597g16nH8cvOmC2Vv2F9wpeqofpAGdzIBaZrPgbL2VC2tZXhFXcyikA9eRT8EPHHsvx5akkgiODqC53f00XmHi0odd'
  stripe_publishable_key: 'pk_test_51K990FSH597g16nHWNnhPTaXqrkOjfl57aJ63IYcJHJv356RkN4NXLiqYfs9vOnXI4taK9KX50lpJ29GhHDd2ChU00F1D3hqzX'