development:
  stripe_secret_key: 'sk_test_51K990FSH597g16nH8cvOmC2Vv2F9wpeqofpAGdzIBaZrPgbL2VC2tZXhFXcyikA9eRT8EPHHsvx5akkgiODqC53f00XmHi0odd'
  stripe_publishable_key: 'pk_test_51K990FSH597g16nHWNnhPTaXqrkOjfl57aJ63IYcJHJv356RkN4NXLiqYfs9vOnXI4taK9KX50lpJ29GhHDd2ChU00F1D3hqzX'
  stripe_price_token_premium: 'price_1L2b3ZSH597g16nHxXO8QrDX'
  stripe_price_token_monthly: 'price_1LC11xSH597g16nH43TMvUgI'
  stripe_price_token_3_month: 'price_1LD02MSH597g16nHwx6WxH5L'
  stripe_price_token_6_month: 'price_1LD03HSH597g16nH0xcZnvSl'
  stripe_price_token_12_month: 'price_1LD044SH597g16nHLnBu1m0i'

  zoho_client_id: '1000.7JII82RGSEMA3RSUCOXA4RZL6PM4BE'
  zoho_client_secret: 'a54e2c40317f8a3f211df6b5697b19f91f3ca04198'
  zoho_refresh_token: '1000.1f60701ed10cd9e4218ce6269fac16d2.9e36c2a7b3f94bb542d5073b9d542d59'
  zoho_redirect_uri: 'http://www.zoho.com/subscriptions'
  zoho_call_back_url: 'http://localhost:3000/user/zoho_call_back'
  zoho_organization_id: '794973394'

test:
  stripe_secret_key: 'sk_test_51K990FSH597g16nH8cvOmC2Vv2F9wpeqofpAGdzIBaZrPgbL2VC2tZXhFXcyikA9eRT8EPHHsvx5akkgiODqC53f00XmHi0odd'
  stripe_publishable_key: 'pk_test_51K990FSH597g16nHWNnhPTaXqrkOjfl57aJ63IYcJHJv356RkN4NXLiqYfs9vOnXI4taK9KX50lpJ29GhHDd2ChU00F1D3hqzX'
  stripe_price_token_premium: 'price_1L2b3ZSH597g16nHxXO8QrDX'
  stripe_price_token_monthly: 'price_1LC11xSH597g16nH43TMvUgI'
  stripe_price_token_3_month: 'price_1LD02MSH597g16nHwx6WxH5L'
  stripe_price_token_6_month: 'price_1LD03HSH597g16nH0xcZnvSl'
  stripe_price_token_12_month: 'price_1LD044SH597g16nHLnBu1m0i'

  zoho_client_id: '1000.7JII82RGSEMA3RSUCOXA4RZL6PM4BE'
  zoho_client_secret: 'a54e2c40317f8a3f211df6b5697b19f91f3ca04198'
  zoho_refresh_token: '1000.1f60701ed10cd9e4218ce6269fac16d2.9e36c2a7b3f94bb542d5073b9d542d59'
  zoho_redirect_uri: 'http://www.zoho.com/subscriptions'
  zoho_call_back_url: 'http://localhost:3000/user/zoho_call_back'
  zoho_organization_id: '794973394'

staging:
  #  Local
  # stripe_secret_key: 'sk_test_51K990FSH597g16nH8cvOmC2Vv2F9wpeqofpAGdzIBaZrPgbL2VC2tZXhFXcyikA9eRT8EPHHsvx5akkgiODqC53f00XmHi0odd'
  # stripe_publishable_key: 'pk_test_51K990FSH597g16nHWNnhPTaXqrkOjfl57aJ63IYcJHJv356RkN4NXLiqYfs9vOnXI4taK9KX50lpJ29GhHDd2ChU00F1D3hqzX'
  # stripe_price_token_premium: 'price_1L2b3ZSH597g16nHxXO8QrDX'
  # stripe_price_token_monthly: 'price_1LC11xSH597g16nH43TMvUgI'
  # stripe_price_token_3_month: 'price_1LD02MSH597g16nHwx6WxH5L'
  # stripe_price_token_6_month: 'price_1LD03HSH597g16nH0xcZnvSl'
  # stripe_price_token_12_month: 'price_1LD044SH597g16nHLnBu1m0i'
  #   Staging 
  # stripe_secret_key: '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'
  # stripe_publishable_key: 'pk_live_51KNukoGhIqmXhERRXCSUTGg2h3LT8ZoiM46Ow6UOEjlYhIyTZCYb3Oy0GohmJUywN7JTTK66NeQJGAht8GF6yjiI00XOMrRVKW'
  
  stripe_secret_key: 'sk_test_51KNukoGhIqmXhERRw75VJiLRuH0fh0aKHBb5NlyLnUeJwiyIOcE0hdsQmkXesH1QVG5stL6KsZGLLQZpXteGH3Y600VoHkdqNW'
  stripe_publishable_key: 'pk_test_51KNukoGhIqmXhERRVRpPQd7Gssth56FLkSbTjiFMSbrpQo4hghe7i211XWLC4rU1LawnuVifYBau7X1KidgRqnl600DUSgtRmD'
  
  stripe_price_token_monthly: 'price_1LMqCnGhIqmXhERRl5piTh77'
  stripe_price_token_3_month: 'price_1LMqEDGhIqmXhERR1KGc3VvP'
  stripe_price_token_6_month: 'price_1LMqF6GhIqmXhERRX4tJVGpA'
  stripe_price_token_12_month: 'price_1LMqGDGhIqmXhERRKII4Qwwq'


  zoho_client_id: '1000.7JII82RGSEMA3RSUCOXA4RZL6PM4BE'
  zoho_client_secret: 'a54e2c40317f8a3f211df6b5697b19f91f3ca04198'
  zoho_refresh_token: '1000.1f60701ed10cd9e4218ce6269fac16d2.9e36c2a7b3f94bb542d5073b9d542d59'
  zoho_redirect_uri: 'http://www.zoho.com/subscriptions'
  zoho_call_back_url: 'http://demo.itslabel.me/user/zoho_call_back'
  zoho_organization_id: '794973394'

production:
  #   Local
  # stripe_secret_key: 'sk_test_51K990FSH597g16nH8cvOmC2Vv2F9wpeqofpAGdzIBaZrPgbL2VC2tZXhFXcyikA9eRT8EPHHsvx5akkgiODqC53f00XmHi0odd'
  # stripe_publishable_key: 'pk_test_51K990FSH597g16nHWNnhPTaXqrkOjfl57aJ63IYcJHJv356RkN4NXLiqYfs9vOnXI4taK9KX50lpJ29GhHDd2ChU00F1D3hqzX'
  # stripe_price_token_premium: 'price_1L2b3ZSH597g16nHxXO8QrDX'
  # stripe_price_token_monthly: 'price_1LC11xSH597g16nH43TMvUgI'
  # stripe_price_token_3_month: 'price_1LD02MSH597g16nHwx6WxH5L'
  # stripe_price_token_6_month: 'price_1LD03HSH597g16nH0xcZnvSl'
  # stripe_price_token_12_month: 'price_1LD044SH597g16nHLnBu1m0i'

  #   Production   
  stripe_secret_key: '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'
  stripe_publishable_key: 'pk_live_51KNukoGhIqmXhERRXCSUTGg2h3LT8ZoiM46Ow6UOEjlYhIyTZCYb3Oy0GohmJUywN7JTTK66NeQJGAht8GF6yjiI00XOMrRVKW'
  
  # stripe_secret_key: 'sk_test_51KNukoGhIqmXhERRw75VJiLRuH0fh0aKHBb5NlyLnUeJwiyIOcE0hdsQmkXesH1QVG5stL6KsZGLLQZpXteGH3Y600VoHkdqNW'
  # stripe_publishable_key: 'pk_test_51KNukoGhIqmXhERRVRpPQd7Gssth56FLkSbTjiFMSbrpQo4hghe7i211XWLC4rU1LawnuVifYBau7X1KidgRqnl600DUSgtRmD'
  
  stripe_price_token_monthly: 'price_1LMqCnGhIqmXhERRl5piTh77'
  stripe_price_token_3_month: 'price_1LMqEDGhIqmXhERR1KGc3VvP'
  stripe_price_token_6_month: 'price_1LMqF6GhIqmXhERRX4tJVGpA'
  stripe_price_token_12_month: 'price_1LMqGDGhIqmXhERRKII4Qwwq'

  zoho_client_id: '1000.7JII82RGSEMA3RSUCOXA4RZL6PM4BE'
  zoho_client_secret: 'a54e2c40317f8a3f211df6b5697b19f91f3ca04198'
  zoho_refresh_token: '1000.1f60701ed10cd9e4218ce6269fac16d2.9e36c2a7b3f94bb542d5073b9d542d59'
  zoho_redirect_uri: 'http://www.zoho.com/subscriptions'
  zoho_call_back_url: 'https://app.itslabel.me/user/zoho_call_back'
  zoho_organization_id: '794973394' #staging key - Test Account
  zoho_organization_id: '794958424' #Production key - Basic Account
