branch-defaults:
  master:
    environment: its-label-me-live-production
    group_suffix: null
global:
  application_name: its-label-me-live
  branch: null
  default_ec2_keyname: itslabelme
  default_platform: Ruby 2.7 running on 64bit Amazon Linux 2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
